from sqlalchemy import create_engine, String, Float
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, sessionmaker


DATABASE_URL = "sqlite:///./database.db"


# The engine is SQLAlchemy's connection/interface to the database. 


engine = create_engine(                            

    DATABASE_URL,
    echo=True,                                            # It prints the SQL queris generated by SQLAlchemy
    connect_args={"check_same_thread": False}
)

#session factory # A session = one unit of work with the DB (begin → queries → commit/rollback → close)
SessionlLocal = sessionmaker(
    bind = engine,
    autoflush = False,
    autocommit = False
)


class Base(DeclarativeBase):
    """Base class for all models"""
    pass


def get_db(SessionlLocal):

    db = SessionlLocal()
    try:
        yield db
    finally:
        db.close()


# class Technician(Base):

#     __tablename__ = "technicians"

#     id: Mapped[int] = mapped_column(primary_key=True)
#     name: Mapped[str] = mapped_column(String(100))
#     city: Mapped[str] = mapped_column(String(100))
#     rating: Mapped[float] = mapped_column(Float)



# Base.metadata.create_all(engine)